/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Dao.ClienteDAO;
import Modelo.Cliente;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmClientes extends javax.swing.JFrame {
    ClienteDAO dao = new ClienteDAO();

DefaultTableModel modelo = new DefaultTableModel();

private int idCliente = 0;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmClientes.class.getName());

    /**
     * Creates new form FrmClientes
     */
public FrmClientes() {

    initComponents();

    btnEliminar.addActionListener(this::btnEliminarActionPerformed);
    btnBuscar.addActionListener(this::btnBuscarActionPerformed);

    listarClientes();
}
private void listarClientes() {

    modelo = (DefaultTableModel) tblClientes.getModel();

    modelo.setRowCount(0);

    List<Cliente> lista = dao.listar();

    for (Cliente c : lista) {

        Object datos[] = {

            c.getId(),
            c.getDni(),
            c.getNombre(),
            c.getTelefono(),
            c.getDireccion(),
            c.getCorreo()

        };

        modelo.addRow(datos);
    }
}

private void limpiar() {

    txtDni.setText("");
    txtNombre.setText("");
    txtTelefono.setText("");
    txtDireccion.setText("");
    txtCorreo.setText("");

    idCliente = 0;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtDni = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DNI :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 29, 67, -1));

        jLabel2.setText("Nombre :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 72, 67, -1));

        jLabel3.setText("Telefono :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 109, 67, -1));

        jLabel4.setText("Direccion :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 146, 67, -1));

        jLabel5.setText("Correo :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 186, 67, -1));

        txtNombre.setText("Nombre");
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 69, 264, -1));

        txtTelefono.setText("Telefono");
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 103, 264, -1));

        txtDireccion.setText("Direccion");
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 143, 264, -1));

        txtCorreo.setText("Correo");
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 183, 264, -1));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "DNI", "Nombre", "Telefono", "Direccion", "Correo"
            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 6, 548, 275));

        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 239, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 239, -1, -1));

        btnEliminar.setText("Eliminar");
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 239, -1, -1));

        btnBuscar.setText("Buscar");
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 239, -1, -1));

        txtDni.setText("DNI");
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 29, 71, -1));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 239, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\ProyectosNetbeans\\SistemaInformatico\\src\\Imagenes\\Botones\\LogoNaranja.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
Cliente c = new Cliente();

    c.setDni(txtDni.getText());
    c.setNombre(txtNombre.getText());
    c.setTelefono(txtTelefono.getText());
    c.setDireccion(txtDireccion.getText());
    c.setCorreo(txtCorreo.getText());

    if (dao.guardar(c)) {

        JOptionPane.showMessageDialog(
                this,
                "Cliente guardado"
        );

        listarClientes();
        limpiar();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Error al guardar"
        );
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
 if(idCliente == 0){

        JOptionPane.showMessageDialog(
                this,
                "Seleccione un cliente de la tabla"
        );

        return;
    }

    Cliente c = new Cliente();

    c.setId(idCliente);
    c.setDni(txtDni.getText());
    c.setNombre(txtNombre.getText());
    c.setTelefono(txtTelefono.getText());
    c.setDireccion(txtDireccion.getText());
    c.setCorreo(txtCorreo.getText());

    if(dao.modificar(c)){

        JOptionPane.showMessageDialog(
                this,
                "Cliente modificado correctamente"
        );

        listarClientes();
        limpiar();
    }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked

    int fila = tblClientes.getSelectedRow();

    idCliente = Integer.parseInt(
            tblClientes.getValueAt(fila, 0).toString()
    );

    txtDni.setText(
            tblClientes.getValueAt(fila, 1).toString()
    );

    txtNombre.setText(
            tblClientes.getValueAt(fila, 2).toString()
    );

    txtTelefono.setText(
            tblClientes.getValueAt(fila, 3).toString()
    );

    txtDireccion.setText(
            tblClientes.getValueAt(fila, 4).toString()
    );

    txtCorreo.setText(
            tblClientes.getValueAt(fila, 5).toString()
    );
System.out.println("ID Cliente = " + idCliente);
    }//GEN-LAST:event_tblClientesMouseClicked

    
    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked

    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
    MenuPrincipal menu = new MenuPrincipal();
    menu.setVisible(true);

    this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed
private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {

if (idCliente == 0) {

        JOptionPane.showMessageDialog(
                this,
                "Seleccione un cliente"
        );

        return;
    }

    if (dao.eliminar(idCliente)) {

        JOptionPane.showMessageDialog(
                this,
                "Cliente eliminado"
        );

        listarClientes();
        limpiar();
    }
}
private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {

    Cliente c = dao.buscarPorDni(
            txtDni.getText()
    );

    if (c.getId() > 0) {

        idCliente = c.getId();

        txtNombre.setText(c.getNombre());
        txtTelefono.setText(c.getTelefono());
        txtDireccion.setText(c.getDireccion());
        txtCorreo.setText(c.getCorreo());

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Cliente no encontrado"
        );
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmClientes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
