/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Dao.ProduccionDAO;
import Modelo.Produccion;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmProduccion extends javax.swing.JFrame {
    
    ProduccionDAO dao = new ProduccionDAO();
    DefaultTableModel modelo = new DefaultTableModel();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmProduccion.class.getName());

    /**
     * Creates new form FrmProduccion
     */
    public FrmProduccion() {
        initComponents();
        listarProduccion();
        cargarFechaActual();
        
        // Configurar campos
        txtId.setVisible(false);
        txtFecha.setEditable(false);
        
        // Action Listeners
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);
        btnModificar.addActionListener(this::btnModificarActionPerformed);
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        
        // Mouse listener para la tabla
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTable1MouseClicked(evt);  // ← CORREGIDO
    }
});
    }

    private void cargarFechaActual() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        txtFecha.setText(sdf.format(new Date()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtFecha = new javax.swing.JTextField();
        txtLote = new javax.swing.JTextField();
        txtSabor = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtObservacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        lgoYogurin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Fecha :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 37, 89, -1));

        jLabel2.setText("Lote :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 71, 89, -1));

        jLabel3.setText("Sabor :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 105, 89, -1));

        jLabel4.setText("Cantidad :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 139, 89, -1));

        jLabel5.setText("Observacion :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 197, 89, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 231, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 231, -1, -1));

        btnLimpiar.setText("Eliminar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        txtFecha.setText("Fecha");
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 34, 169, -1));

        txtLote.setText("Lote");
        txtLote.addActionListener(this::txtLoteActionPerformed);
        getContentPane().add(txtLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 68, 169, -1));

        txtSabor.setText("Sabor");
        txtSabor.addActionListener(this::txtSaborActionPerformed);
        getContentPane().add(txtSabor, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 102, 169, -1));

        txtCantidad.setText("Cantidad");
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 136, 169, -1));

        txtObservacion.setText("Observacion");
        getContentPane().add(txtObservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 191, 169, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Fecha", "Lote", "Sabor", "Cantidad", "Observacion", "PrecioVenta"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 19, 570, 275));

        jLabel6.setText("ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 12, 37, -1));

        txtId.setText("Id");
        txtId.addActionListener(this::txtIdActionPerformed);
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 6, 71, -1));

        jLabel7.setText("Precio");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 167, 56, -1));
        getContentPane().add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 164, 71, -1));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        lgoYogurin.setIcon(new javax.swing.ImageIcon("D:\\ProyectosNetbeans\\SistemaInformatico\\src\\Imagenes\\Botones\\LOGO.png")); // NOI18N
        getContentPane().add(lgoYogurin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents
// ========== MÉTODOS CRUD ==========

    public void listarProduccion() {
        modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);

        List<Produccion> lista = dao.listar();

        for (Produccion p : lista) {
            Object datos[] = {
                p.getId(),
                p.getFecha(),
                p.getLote(),
                p.getSabor(),
                p.getCantidad(),
                p.getObservacion(),
                p.getPrecioVenta()
            };
            modelo.addRow(datos);
        }
    }

    private void limpiarCampos() {
        txtId.setText("");
        txtLote.setText("");
        txtSabor.setText("");
        txtCantidad.setText("");
        txtObservacion.setText("");
        cargarFechaActual();
        txtPrecioVenta.setText("");
    }
    private void txtSaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaborActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaborActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
 try {
            // Validaciones
            if (txtLote.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese el lote");
                return;
            }
            if (txtSabor.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese el sabor");
                return;
            }
            if (txtCantidad.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese la cantidad");
                return;
            }

            Produccion p = new Produccion();
            p.setFecha(txtFecha.getText());
            p.setLote(txtLote.getText());
            p.setSabor(txtSabor.getText());
            p.setCantidad(Integer.parseInt(txtCantidad.getText()));
            p.setObservacion(txtObservacion.getText());
            p.setPrecioVenta(Double.parseDouble(txtPrecioVenta.getText()));

            if (dao.guardar(p)) {
                JOptionPane.showMessageDialog(this, "Producción registrada correctamente");
                listarProduccion();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser un número válido");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro primero");
            return;
        }

        try {
            Produccion p = new Produccion();
            p.setId(Integer.parseInt(txtId.getText()));
            p.setFecha(txtFecha.getText());
            p.setLote(txtLote.getText());
            p.setSabor(txtSabor.getText());
            p.setCantidad(Integer.parseInt(txtCantidad.getText()));
            p.setObservacion(txtObservacion.getText());
            p.setPrecioVenta(Double.parseDouble(txtPrecioVenta.getText()));

            if (dao.modificar(p)) {
                JOptionPane.showMessageDialog(this, "Producción modificada correctamente");
                listarProduccion();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser un número válido");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        try {
            if (txtId.getText() == null || txtId.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Seleccione un registro primero");
                return;
            }
            
            int id = Integer.parseInt(txtId.getText().trim());
            
            int confirm = JOptionPane.showConfirmDialog(this, 
                "¿Está seguro de eliminar esta producción?", 
                "Confirmar", 
                JOptionPane.YES_NO_OPTION);
            
            if (confirm == JOptionPane.YES_OPTION) {
                if (dao.eliminar(id)) {
                    JOptionPane.showMessageDialog(this, "Producción eliminada correctamente");
                    listarProduccion();
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al eliminar");
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID inválido");
        }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int fila = jTable1.getSelectedRow();
        if (fila >= 0) {
            txtId.setText(jTable1.getValueAt(fila, 0).toString());
            txtFecha.setText(jTable1.getValueAt(fila, 1).toString());
            txtLote.setText(jTable1.getValueAt(fila, 2).toString());
            txtSabor.setText(jTable1.getValueAt(fila, 3).toString());
            txtCantidad.setText(jTable1.getValueAt(fila, 4).toString());
            txtObservacion.setText(jTable1.getValueAt(fila, 5).toString());
            txtPrecioVenta.setText(jTable1.getValueAt(fila, 6).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);

        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lgoYogurin;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtObservacion;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtSabor;
    // End of variables declaration//GEN-END:variables
}