/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Dao.ReporteDAO;
/**
 *
 * @author hagi1
 */
public class FrmReportes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmReportes.class.getName());
    ReporteDAO dao = new ReporteDAO();

    /**
     * Creates new form FrmReportes
     */
    public FrmReportes() {
        initComponents();
            btnVentasDia.addActionListener(e -> cargarVentasDia());
            btnVentasMes.addActionListener(e -> cargarVentasMes());
            btnProduccion.addActionListener(e -> cargarProduccion());
            btnStockCritico.addActionListener(e -> cargarStockCritico());
            btnCierreCaja.addActionListener(e -> cargarCierreCaja());
            
            btnExportarReporte.addActionListener(e -> exportarReporte());
            btnCerrarReporte.addActionListener(e -> dispose());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void cargarVentasDia(){

    tblReportes.setModel(
            dao.ventasDia()
    );
}
    private void cargarVentasMes(){
    
        tblReportes.setModel(dao.ventasMes());
    }
    
    private void cargarProduccion() {
        
    tblReportes.setModel(dao.reporteProduccion());
    }
    
    private void cargarStockCritico(){
    
        tblReportes.setModel(dao.stockCritico());
    }
    
    private void cargarCierreCaja(){
    
        tblReportes.setModel(dao.cierreCaja());
    }
    
    private void exportarReporte() {

    try {

        javax.swing.JFileChooser chooser =
                new javax.swing.JFileChooser();

        int opcion = chooser.showSaveDialog(this);

        if (opcion == javax.swing.JFileChooser.APPROVE_OPTION) {

            java.io.File archivo =
                    chooser.getSelectedFile();

            java.io.PrintWriter pw =
                    new java.io.PrintWriter(archivo + ".csv");

            for (int i = 0; i < tblReportes.getColumnCount(); i++) {

                pw.print(tblReportes.getColumnName(i));

                if (i < tblReportes.getColumnCount() - 1) {
                    pw.print(",");
                }
            }

            pw.println();

            for (int fila = 0; fila < tblReportes.getRowCount(); fila++) {

                for (int col = 0; col < tblReportes.getColumnCount(); col++) {

                    pw.print(tblReportes.getValueAt(fila, col));

                    if (col < tblReportes.getColumnCount() - 1) {
                        pw.print(",");
                    }
                }

                pw.println();
            }

            pw.close();

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Reporte exportado correctamente"
            );
        }

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error al exportar: " + e.getMessage()
        );
    }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVentasDia = new javax.swing.JButton();
        btnVentasMes = new javax.swing.JButton();
        btnProduccion = new javax.swing.JButton();
        btnStockCritico = new javax.swing.JButton();
        btnCierreCaja = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReportes = new javax.swing.JTable();
        btnExportarReporte = new javax.swing.JButton();
        btnCerrarReporte = new javax.swing.JButton();
        lgoReportes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PANEL DE BOTONES DE REPORTES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 14, -1, -1));

        btnVentasDia.setText("Ventas del Dia");
        getContentPane().add(btnVentasDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 48, -1, -1));

        btnVentasMes.setText("Ventas Mensuales");
        btnVentasMes.addActionListener(this::btnVentasMesActionPerformed);
        getContentPane().add(btnVentasMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 48, -1, -1));

        btnProduccion.setText("Produccion");
        getContentPane().add(btnProduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 48, -1, -1));

        btnStockCritico.setText("Stock Critico");
        getContentPane().add(btnStockCritico, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 48, -1, -1));

        btnCierreCaja.setText("Cierre de Caja");
        getContentPane().add(btnCierreCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 48, -1, -1));

        tblReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "REPORTE", "FECHA", "DESCRIPCION", "ESTADO"
            }
        ));
        jScrollPane1.setViewportView(tblReportes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 83, 606, 275));

        btnExportarReporte.setText("Exportar Reporte");
        getContentPane().add(btnExportarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 391, -1, -1));

        btnCerrarReporte.setText("Cerrar Ventana");
        getContentPane().add(btnCerrarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 391, -1, -1));

        lgoReportes.setIcon(new javax.swing.ImageIcon("D:\\ProyectosNetbeans\\SistemaInformatico\\src\\Imagenes\\Botones\\LogoReporte.png")); // NOI18N
        getContentPane().add(lgoReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentasMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentasMesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmReportes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarReporte;
    private javax.swing.JButton btnCierreCaja;
    private javax.swing.JButton btnExportarReporte;
    private javax.swing.JButton btnProduccion;
    private javax.swing.JButton btnStockCritico;
    private javax.swing.JButton btnVentasDia;
    private javax.swing.JButton btnVentasMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lgoReportes;
    private javax.swing.JTable tblReportes;
    // End of variables declaration//GEN-END:variables
}
