/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import controlador.ReporteControlador;
/**
 *
 * @author hagi1
 */
public class FrmReportes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmReportes.class.getName());
    ReporteControlador control = new ReporteControlador(); // (luiggi) la vista solo habla con el controlador

    private final controlador.ExportacionControlador exportar =
            new controlador.ExportacionControlador();          // (luiggi) genera PDF y Excel (RF-24)

    private String tituloActual = "Reporte";                   // (luiggi) rotulo del reporte en pantalla

    /**
     * Creates new form FrmReportes
     */
    public FrmReportes() {
        initComponents();
            btnVentasDia.addActionListener(e -> cargarVentasDia());
            btnVentasMes.addActionListener(e -> cargarVentasMes());
            btnProduccion.addActionListener(e -> cargarProduccion());
            btnStockCritico.addActionListener(e -> cargarStockCritico());
            btnCierreCaja.addActionListener(e -> cargarCierreCaja());
            
            btnExportarReporte.addActionListener(e -> exportarReporte());
            btnCerrarReporte.addActionListener(e -> dispose());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void cargarVentasDia() {
        tituloActual = "Reporte de ventas del dia";      // (luiggi) rotula el PDF que se exporte
        tblReportes.setModel(control.ventasDia());
    }

    private void cargarVentasMes() {
        tituloActual = "Reporte de ventas del mes";
        tblReportes.setModel(control.ventasMes());
    }

    private void cargarProduccion() {
        tituloActual = "Reporte de produccion";
        tblReportes.setModel(control.reporteProduccion());
    }

    private void cargarStockCritico() {
        tituloActual = "Productos en stock critico";
        tblReportes.setModel(control.stockCritico());
    }

    private void cargarCierreCaja() {
        tituloActual = "Cierre de caja del dia";
        tblReportes.setModel(control.cierreCaja());
    }
    
    /**
     * Exporta a PDF o a Excel el reporte que se esta viendo en pantalla (RF-24).
     * La generacion del archivo la hace el controlador.
     */
    private void exportarReporte() {

        javax.swing.table.DefaultTableModel datos =
                (javax.swing.table.DefaultTableModel) tblReportes.getModel();

        if (datos.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Primero cargue un reporte");
            return;                                          // (luiggi) no exporta una tabla vacia
        }

        String[] opciones = {"PDF", "Excel", "Cancelar"};

        int eleccion = javax.swing.JOptionPane.showOptionDialog(this,
                "En que formato desea exportar el reporte?",
                "Exportar", javax.swing.JOptionPane.DEFAULT_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);

        if (eleccion != 0 && eleccion != 1) {
            return;                                          // (luiggi) el usuario cancelo
        }

        boolean esPdf = (eleccion == 0);
        String extension = esPdf ? "pdf" : "csv";

        java.io.File destino = new java.io.File(
                exportar.carpetaDocumentos(),
                exportar.nombreReporte(tituloActual, extension)); // (luiggi) nombre con fecha y hora

        controlador.Resultado r = esPdf
                ? exportar.exportarPdf(destino, tituloActual, datos)
                : exportar.exportarExcel(destino, datos);

        javax.swing.JOptionPane.showMessageDialog(this, r.getMensaje(),
                r.esExito() ? "Listo" : "Error",
                r.esExito() ? javax.swing.JOptionPane.INFORMATION_MESSAGE
                            : javax.swing.JOptionPane.ERROR_MESSAGE);

        if (r.esExito()) {
            abrirArchivo(destino);                           // (luiggi) muestra el documento generado
        }
    }

    /** Abre el documento con el programa que el sistema tenga asociado. */
    private void abrirArchivo(java.io.File archivo) {
        try {
            if (java.awt.Desktop.isDesktopSupported()) {
                java.awt.Desktop.getDesktop().open(archivo);
            }
        } catch (java.io.IOException e) {
            // El archivo ya quedo guardado; no poder abrirlo no es un fallo de la exportacion
            System.err.println("No se pudo abrir el documento: " + e.getMessage());
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVentasDia = new javax.swing.JButton();
        btnVentasMes = new javax.swing.JButton();
        btnProduccion = new javax.swing.JButton();
        btnStockCritico = new javax.swing.JButton();
        btnCierreCaja = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReportes = new javax.swing.JTable();
        btnExportarReporte = new javax.swing.JButton();
        btnCerrarReporte = new javax.swing.JButton();
        lgoReportes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PANEL DE BOTONES DE REPORTES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 14, -1, -1));

        btnVentasDia.setText("Ventas del Dia");
        getContentPane().add(btnVentasDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 48, -1, -1));

        btnVentasMes.setText("Ventas Mensuales");
        btnVentasMes.addActionListener(this::btnVentasMesActionPerformed);
        getContentPane().add(btnVentasMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 48, -1, -1));

        btnProduccion.setText("Produccion");
        getContentPane().add(btnProduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 48, -1, -1));

        btnStockCritico.setText("Stock Critico");
        getContentPane().add(btnStockCritico, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 48, -1, -1));

        btnCierreCaja.setText("Cierre de Caja");
        getContentPane().add(btnCierreCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 48, -1, -1));

        tblReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "REPORTE", "FECHA", "DESCRIPCION", "ESTADO"
            }
        ));
        jScrollPane1.setViewportView(tblReportes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 83, 606, 275));

        btnExportarReporte.setText("Exportar Reporte");
        getContentPane().add(btnExportarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 391, -1, -1));

        btnCerrarReporte.setText("Cerrar Ventana");
        getContentPane().add(btnCerrarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 391, -1, -1));

        lgoReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/LogoReporte.png"))); // NOI18N
        getContentPane().add(lgoReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentasMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentasMesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmReportes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarReporte;
    private javax.swing.JButton btnCierreCaja;
    private javax.swing.JButton btnExportarReporte;
    private javax.swing.JButton btnProduccion;
    private javax.swing.JButton btnStockCritico;
    private javax.swing.JButton btnVentasDia;
    private javax.swing.JButton btnVentasMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lgoReportes;
    private javax.swing.JTable tblReportes;
    // End of variables declaration//GEN-END:variables
}
