/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Dao.ReporteDAO;
/**
 *
 * @author hagi1
 */
public class FrmReportes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmReportes.class.getName());
    ReporteDAO dao = new ReporteDAO();

    /**
     * Creates new form FrmReportes
     */
    public FrmReportes() {
        initComponents();
            btnVentasDia.addActionListener(
    e -> cargarVentasDia()
    );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void cargarVentasDia(){

    tblReportes.setModel(
            dao.ventasDia()
    );
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVentasDia = new javax.swing.JButton();
        btnVentasMes = new javax.swing.JButton();
        btnProduccion = new javax.swing.JButton();
        btnStockCritico = new javax.swing.JButton();
        btnCierreCaja = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReportes = new javax.swing.JTable();
        btnExportarReporte = new javax.swing.JButton();
        btnCerrarReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PANEL DE BOTONES DE REPORTES");

        btnVentasDia.setText("Ventas del Dia");

        btnVentasMes.setText("Ventas Mensuales");
        btnVentasMes.addActionListener(this::btnVentasMesActionPerformed);

        btnProduccion.setText("Produccion");

        btnStockCritico.setText("Stock Critico");

        btnCierreCaja.setText("Cierre de Caja");

        tblReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "REPORTE", "FECHA", "DESCRIPCION", "ESTADO"
            }
        ));
        jScrollPane1.setViewportView(tblReportes);

        btnExportarReporte.setText("Exportar Reporte");

        btnCerrarReporte.setText("Cerrar Ventana");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVentasDia)
                                .addGap(18, 18, 18)
                                .addComponent(btnVentasMes)
                                .addGap(18, 18, 18)
                                .addComponent(btnProduccion)
                                .addGap(18, 18, 18)
                                .addComponent(btnStockCritico)
                                .addGap(18, 18, 18)
                                .addComponent(btnCierreCaja))
                            .addComponent(jLabel1))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btnExportarReporte)
                        .addGap(98, 98, 98)
                        .addComponent(btnCerrarReporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVentasDia)
                    .addComponent(btnVentasMes)
                    .addComponent(btnProduccion)
                    .addComponent(btnStockCritico)
                    .addComponent(btnCierreCaja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportarReporte)
                    .addComponent(btnCerrarReporte))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentasMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentasMesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmReportes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarReporte;
    private javax.swing.JButton btnCierreCaja;
    private javax.swing.JButton btnExportarReporte;
    private javax.swing.JButton btnProduccion;
    private javax.swing.JButton btnStockCritico;
    private javax.swing.JButton btnVentasDia;
    private javax.swing.JButton btnVentasMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReportes;
    // End of variables declaration//GEN-END:variables
}
