/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        btnInsumos.setText("Insumos");
        btnUsuarios.addActionListener(this::btnUsuariosActionPerformed);
        btnProductos.addActionListener(this::btnProductosActionPerformed);
        btnClientes.addActionListener(this::btnClientesActionPerformed);
        btnInsumos.addActionListener(this::btnInsumosActionPerformed);
        btnProduccion.addActionListener(this::btnProduccionActionPerformed);
        btnVentas.addActionListener(this::btnVentasActionPerformed);
        btnInventario.addActionListener(this::btnInventarioActionPerformed);
        btnReportes.addActionListener(this::btnReportesActionPerformed);
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUsuarios = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnInsumos = new javax.swing.JButton();
        btnProduccion = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        lgoInicial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUsuarios.setText("Usuarios");
        getContentPane().add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 29, 91, -1));

        btnProductos.setText("Productos");
        btnProductos.addActionListener(this::btnProductosActionPerformed);
        getContentPane().add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 91, -1));

        btnInsumos.setText("Insumos");
        btnInsumos.addActionListener(this::btnInsumosActionPerformed);
        getContentPane().add(btnInsumos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 133, 91, -1));

        btnProduccion.setText("Produccion");
        getContentPane().add(btnProduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 191, -1, -1));

        btnClientes.setText("Clientes");
        getContentPane().add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 29, 83, -1));

        btnVentas.setText("Ventas");
        getContentPane().add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 83, -1));

        btnInventario.setText("Inventario");
        getContentPane().add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 133, -1, -1));

        btnReportes.setText("Reportes");
        getContentPane().add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 191, 83, -1));

        btnCerrarSesion.setText("Cerrar Sesion");
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 232, -1, -1));

        lgoInicial.setIcon(new javax.swing.ImageIcon("D:\\ProyectosNetbeans\\SistemaInformatico\\src\\Imagenes\\Botones\\LogoPrincipal.png")); // NOI18N
        getContentPane().add(lgoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsumosActionPerformed
        new FrmInsumos().setVisible(true);
    }//GEN-LAST:event_btnInsumosActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
new FrmProductos().setVisible(true);    }//GEN-LAST:event_btnProductosActionPerformed
private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {

    new FrmUsuarios().setVisible(true);

}


private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {

    new FrmClientes().setVisible(true);

}

private void btnProduccionActionPerformed(java.awt.event.ActionEvent evt) {

    new FrmProduccion().setVisible(true);

}

private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {

    new FrmVentas().setVisible(true);

}

private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {

    new FrmInventario().setVisible(true);

}

private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {

    new FrmReportes().setVisible(true);

}

private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {

    this.dispose();

    new LoginForm().setVisible(true);

}
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnInsumos;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnProduccion;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel lgoInicial;
    // End of variables declaration//GEN-END:variables
}
