/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        btnInsumos.setText("Insumos");
        btnUsuarios.addActionListener(this::btnUsuariosActionPerformed);
        btnProductos.addActionListener(this::btnProductosActionPerformed);
        btnClientes.addActionListener(this::btnClientesActionPerformed);
        btnInsumos.addActionListener(this::btnInsumosActionPerformed);
        btnProduccion.addActionListener(this::btnProduccionActionPerformed);
        btnVentas.addActionListener(this::btnVentasActionPerformed);
        btnInventario.addActionListener(this::btnInventarioActionPerformed);
        btnReportes.addActionListener(this::btnReportesActionPerformed);
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUsuarios = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnInsumos = new javax.swing.JButton();
        btnProduccion = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnUsuarios.setText("Usuarios");

        btnProductos.setText("Productos");
        btnProductos.addActionListener(this::btnProductosActionPerformed);

        btnInsumos.setText("Insumos");
        btnInsumos.addActionListener(this::btnInsumosActionPerformed);

        btnProduccion.setText("Produccion");

        btnClientes.setText("Clientes");

        btnVentas.setText("Ventas");

        btnInventario.setText("Inventario");

        btnReportes.setText("Reportes");

        btnCerrarSesion.setText("Cerrar Sesion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInsumos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(btnCerrarSesion)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsuarios)
                    .addComponent(btnClientes))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProductos)
                    .addComponent(btnVentas))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsumos)
                    .addComponent(btnInventario))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProduccion)
                    .addComponent(btnReportes))
                .addGap(18, 18, 18)
                .addComponent(btnCerrarSesion)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsumosActionPerformed
        new FrmInsumos().setVisible(true);
    }//GEN-LAST:event_btnInsumosActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
new FrmProductos().setVisible(true);    }//GEN-LAST:event_btnProductosActionPerformed
private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {

    new FrmUsuarios().setVisible(true);

}


private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {

    new FrmClientes().setVisible(true);

}

private void btnProduccionActionPerformed(java.awt.event.ActionEvent evt) {

    new FrmProduccion().setVisible(true);

}

private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {

    new FrmVentas().setVisible(true);

}

private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {

    new FrmInventario().setVisible(true);

}

private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {

    new FrmReportes().setVisible(true);

}

private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {

    this.dispose();

    new LoginForm().setVisible(true);

}
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnInsumos;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnProduccion;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVentas;
    // End of variables declaration//GEN-END:variables
}
